name = "kafka-worker"
main = "src/index.ts"
compatibility_date = "2022-08-21"

[vars]
HOSTNAME="kafka-worker.archmap.workers.dev"

[durable_objects]
bindings = [{name="CLUSTER", class_name="Cluster"}]

[[migrations]]
tag = "v1"
new_classes = ["Cluster"]
