name = "kafka-worker"
main = "dist/index.mjs"
compatibility_date = "2022-08-21"

[build]
command = "node build.js"

[vars]
HOSTNAME="localhost"
PORT="8787"
PARTITION_CHUNK_SIZE="4096"

[durable_objects]
bindings = [
  {name="CLUSTER", class_name="Cluster"},
  {name="PARTITION", class_name="Partition"},
]

[[migrations]]
tag = "v1"
new_classes = ["Cluster"]

[[migrations]]
tag = "v2"
new_classes = ["Session"]

[[migrations]]
tag = "v3"
new_classes = ["Partition"]

[[migrations]]
tag = "v4"
deleted_classes = ["Session"]
